set -g base-index 1
#set -g default-terminal "xterm-256color"
##set -g default-terminal "screen-256color"
set-window-option -g mode-keys vi
set-window-option -g xterm-keys on

set -g prefix C-a
bind C-a send-prefix

bind-key v split-window -h
bind-key s split-window -v

bind-key J resize-pane -D 5
bind-key K resize-pane -U 5
bind-key H resize-pane -L 5
bind-key L resize-pane -R 5

bind-key M-j resize-pane -D
bind-key M-k resize-pane -U
bind-key M-h resize-pane -L
bind-key M-l resize-pane -R

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Use Alt-vim keys without prefix key to switch panes
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5
bind-key -n M-6 select-window -t 6
bind-key -n M-7 select-window -t 7
bind-key -n M-8 select-window -t 8
bind-key -n M-9 select-window -t 9

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# No delay for escape key press
set -sg escape-time 0

# Reload tmux config
bind r source-file ~/.tmux.conf

setw -g aggressive-resize on

bind -n M-t split-window -l 10 'ctags -RV; read'
bind -n M-s split-window -l 10 'exec bash'
bind -n M-v split-window -l 10 'vagrant up && vagrant ssh'

set-option -ga terminal-overrides ",xterm-256color:Tc"

######################
### DESIGN CHANGES ###
######################

## Status bar design
# status line
set -g status-justify left
set -g status-bg black
set -g status-fg red
set -g status-interval 2

# window status
setw -g window-status-format " #F#I:#W#F "
setw -g window-status-current-format " #F#I:#W#F "
#setw -g window-status-format "#[fg=white]#[bg=black] #I #[fg=white]#[bg=black] #W "
#setw -g window-status-format "#[fg=8,bg=black]#I #W"
setw -g window-status-current-format "#[fg=cyan] #I #[fg=cyan] #W "

#set -g default-terminal 'screen-256color'
#set -ga terminal-overrides ',screen-256color:Tc'

# Info on left (I don't have a session display for now)
#set -g status-left ''

## loud or quiet?
#set-option -g visual-activity off
#set-option -g visual-bell off
#set-option -g visual-silence off
#set-window-option -g monitor-activity off
#set-option -g bell-action none

##set -g default-terminal "screen-256color"
##set -g default-terminal "st-256color"

## The panes {

#set -g pane-border-bg blue
#set -g pane-border-fg white
#set -g pane-active-border-bg black
#set -g pane-active-border-fg white

## }
## The statusbar {

#set -g status-position bottom
#set -g status-bg blue
#set -g status-fg white
#set -g status-attr dim
#set -g status-left '#[fg=white,bg=blue,bold][#S]'
#set -g status-right '#[fg=white,bg=blue,bold] %d/%m #[fg=white,bg=blue,bold] %H:%M:%S '
#set -g status-right-length 50
#set -g status-left-length 50

#setw -g window-status-current-fg magenta
#setw -g window-status-current-bg blue
#setw -g window-status-current-attr bold
#setw -g window-status-current-format ' #I#[fg=white]:#[fg=white]#W#[fg=white]#F '

#setw -g window-status-fg white
#setw -g window-status-bg blue
#setw -g window-status-attr none
#setw -g window-status-format ' #I#[fg=white]:#[fg=white]#W#[fg=white]#F '

#setw -g window-status-bell-attr bold
#setw -g window-status-bell-fg colour255
#setw -g window-status-bell-bg colour1

## }
## The messages {

#set -g message-attr bold
#set -g message-fg colour232
#set -g message-bg colour166

## }
